/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Courier_Management_System.Customer;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author apil
 */
public class CustomerRegistration extends javax.swing.JFrame {

    
    
    
    
    public CustomerRegistration() {
        initComponents();
        
        
    }
    public int generateId() throws IOException {
        
        int maxId = 2210;
        String s;
        BufferedReader br; 
        StringTokenizer st;
        File CustomerFile = new File("CustomerFile.txt");
        br = new BufferedReader(new FileReader(CustomerFile));
        if (CustomerFile.exists()) {
            while((s=br.readLine())!=null) {
                st = new StringTokenizer(s, ",");
                
                String i = st.nextToken();
                int uId = Integer.parseInt(i);
                if(maxId<uId) {
                    maxId=uId;
                }
            }
        }
        else {
            maxId+=1;
            
        }
        
        br.close();
        
        return maxId+1;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_massage1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_Name1 = new javax.swing.JTextField();
        jTextField1_Address1 = new javax.swing.JTextField();
        jTextField1_Email = new javax.swing.JTextField();
        jButton1_save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_ContactNumber1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1_reset1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1_userName1 = new javax.swing.JTextField();
        jButton1_close = new javax.swing.JButton();
        jTextField1_password1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1_massage1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Tuki");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("Courier");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Customer Registration Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(162, 162, 162)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jLabel4.setText("Username:");

        jLabel5.setText("Full Name:");

        jLabel6.setText("Address:");

        jLabel7.setText("Contact Number:");

        jTextField1_Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_Name1ActionPerformed(evt);
            }
        });

        jTextField1_Email.setToolTipText("");

        jButton1_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_save.setText("Submit");
        jButton1_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_saveActionPerformed(evt);
            }
        });

        jLabel8.setText("Email:");

        jTextField1_ContactNumber1.setToolTipText("");

        jButton1_reset1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_reset1.setText("Reset");
        jButton1_reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_reset1ActionPerformed(evt);
            }
        });

        jLabel12.setText("password:");

        jTextField1_userName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_userName1ActionPerformed(evt);
            }
        });

        jButton1_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_close.setText("Back");
        jButton1_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_massage1Layout = new javax.swing.GroupLayout(jPanel1_massage1);
        jPanel1_massage1.setLayout(jPanel1_massage1Layout);
        jPanel1_massage1Layout.setHorizontalGroup(
            jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1_massage1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_massage1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1_massage1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1_password1)
                    .addComponent(jTextField1_userName1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_massage1Layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jButton1_save)))
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_massage1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1_reset1)
                        .addGap(84, 84, 84)
                        .addComponent(jButton1_close)
                        .addGap(291, 291, 291))
                    .addGroup(jPanel1_massage1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_massage1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1_Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1_massage1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(79, 79, 79)
                                    .addComponent(jTextField1_ContactNumber1))
                                .addGroup(jPanel1_massage1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(133, 133, 133)
                                    .addComponent(jTextField1_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1_massage1Layout.setVerticalGroup(
            jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_massage1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_userName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1_password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_ContactNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1_massage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_close)
                    .addComponent(jButton1_reset1)
                    .addComponent(jButton1_save))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_massage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_massage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_Name1ActionPerformed

    private void jButton1_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_saveActionPerformed
        
    FileWriter  fw;
    BufferedWriter bw;
    user ur = new user();

    String usern  = this.jTextField1_userName1.getText();
    String passd = this.jTextField1_password1.getText();
    String fullname = this.jTextField1_Name1.getText();
    String address = this.jTextField1_Address1.getText();
    String contact = this.jTextField1_ContactNumber1.getText();
    String email = this.jTextField1_Email.getText();

    ur.setUsern(usern);
    ur.setPassd(passd);
    ur.setFullname(fullname);
    ur.setAddress(address);
    ur.setContact(contact);
    ur.setEmail(email);
    if(usern.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please fill Username!!");
    }
    if(passd.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please fill Password!!");
    }
    if(fullname.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please fill Name!!");
    }
    if(address.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please fill Address!!");
    }
    if(contact.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please fill Contact Number!!");
    }
    if(email.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please fill Email!!");
    }
        else
        {
             JOptionPane.showMessageDialog(null, "Successfully Submit");
             this.hide();
             login cl =new login();
             cl.setVisible(true);
        }
    File CustomerFile = new File("CustomerFile.txt");
    if(!CustomerFile.exists())
        {
        try {
            CustomerFile.createNewFile();

            fw = new FileWriter(CustomerFile, true);
            bw = new BufferedWriter(fw);
            int id = generateId();
            String uID = String.valueOf(id);

            bw.write(uID+","+ur.getUsern()+","+ ur.getPassd()+","+ ur.getFullname() +","+ ur.getAddress() +","+ ur.getContact() +","+ ur.getEmail());
            bw.newLine();
            bw.flush();
            bw.close();
            
            } catch (IOException ex) {
                Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try{
                fw = new FileWriter(CustomerFile, true);
                bw = new BufferedWriter(fw);
                int id = generateId();
                String uID = String.valueOf(id);

                bw.write(uID+","+ur.getUsern()+","+ ur.getPassd()+","+ ur.getFullname() +","+ ur.getAddress() +","+ ur.getContact() +","+ ur.getEmail());
                bw.newLine();
                bw.flush();
                bw.close();
                
                } catch (IOException ex) {
                    Logger.getLogger(CustomerRegistration.class.getName()).log(Level.SEVERE, null, ex);
                }
        }      
    }//GEN-LAST:event_jButton1_saveActionPerformed

    private void jTextField1_userName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_userName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_userName1ActionPerformed

    private void jButton1_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_closeActionPerformed
        // TODO add your handling code here:
        this.hide();
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton1_closeActionPerformed

    private void jButton1_reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_reset1ActionPerformed
        // TODO add your handling code here:
        jTextField1_userName1.setText("");
        jTextField1_password1.setText("");
        jTextField1_Name1.setText("");
        jTextField1_Address1.setText("");
        jTextField1_ContactNumber1.setText("");
        jTextField1_Email.setText("");
    }//GEN-LAST:event_jButton1_reset1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_close;
    private javax.swing.JButton jButton1_reset1;
    private javax.swing.JButton jButton1_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1_massage1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1_Address1;
    private javax.swing.JTextField jTextField1_ContactNumber1;
    private javax.swing.JTextField jTextField1_Email;
    private javax.swing.JTextField jTextField1_Name1;
    private javax.swing.JPasswordField jTextField1_password1;
    private javax.swing.JTextField jTextField1_userName1;
    // End of variables declaration//GEN-END:variables

    private void ID() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
